### PR TITLE
reinforcement learning: pong

### PR DESCRIPTION
**Pull request by dizcology**
Based on http://karpathy.github.io/2016/05/31/rl/

### CODE REVIEW

**Comment by puneith** [comment]
@dizcology This is a great example but I am trying to see what ML on GCP value do we bring. We should show how to run this on GKE or may be you already have plans? Also some of the patterns we use here like feed_dict should be replaced by input queues (in future datasets). Please also include license in the code.

**Comment by dizcology** [comment]
I haven't attempted it yet, but parallelizing the training (on perhaps CMLE) makes a lot of sense.  The training procedure is to play a batch of episodes (each episode is until one of the players reaches 21 points) before updating the weights.  And the episodes in a single batch could be played in parallel.

**Comment by nkashy1** [comment]
@dizcology , @puneith : I think the sample would have a lot of value if we showed people how to do distributed reinforcement learning on ML Engine. It would require the changes you mentioend (e.g. `feed_dict` -> input queues -> datasets and also perhaps wrapping up in estimators).

@dizcology , if you are interested, we can take that up this quarter (or next). With the introduction of [Dataset.from_generator](https://www.tensorflow.org/api_docs/python/tf/contrib/data/Dataset#from_generator), we may be able to formulate a nicer solution to the estimator wrapping problem than the one we came up with previously.

**Comment by puneith** [comment]
Fwiw there is a KR which addresses the lift and shift from some code to running it on CMLE and I am pushing for it.

**Pull request closed without merging**
